### ISSUE TITLE
Change some classes from Internal to public

### ISSUE THREAD

**Issue by LindebergC** [ErikHen/PictureRenderer#19]
I have some clients that used https://github.com/vnbaaij/ImageProcessor.Web.Episerver for cms 11, that used some methods in PictureUtils. 

It would be nice to be able to use some of the methods in the class PictureUtils but the class is Internal, would it be possible to change that to public for PictureUtils and PictureData?

**Comment by ErikHen** [comment]
Hi. Sure, that can be done. What methods do you want to use?

**Comment by LindebergC** [comment]
Wonderful! :) 

Mainly GetPictureData, but that is already public but I was thinking of 

internal static class PictureUtils

to 
public static class PictureUtils

and 
internal class PictureData

to 
public class PictureData

**Comment by ErikHen** [comment]
Hi. Update to v3.11 and see if that works for you. 
I'm curious why you want to do this. Do you render an img/picture element yourself?

**Comment by LindebergC** [comment]
Thank you Erik! It works like a charm! 

Yes you are right, in some places I need to render just the img element, one example is for the meta property="og:image" for facebook.
