### ISSUE TITLE
Attributes without whitespace between them is not valid html

### ISSUE THREAD

**Issue by w82n** [ErikHen/PictureRenderer#6]
https://github.com/ErikHen/PictureRenderer/blob/5b2f95d9708a0421e7684f29b5f7c609b3dad4a7/PictureRenderer/Picture.cs#L88
could you please add white space between the attributes!

**Comment by ErikHen** [comment]
I tried to find information if it was valid or not when I built it. Now I have taken a look in the W3C XML (=XHTML) specification, and it seems that you are correct. Will change it asap.
Thanks
